// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyPatch(arg1:string,arg2:main.PatchFile):Promise<main.PatchResult>;

export function BrowseAsar():Promise<main.AsarInfo>;

export function DetectAsar():Promise<Array<main.AsarInfo>>;

export function GetPatches():Promise<Array<main.PatchFile>>;

export function SelectAsar(arg1:string):Promise<main.AsarInfo>;
