// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPatch(arg1, arg2) {
  return window['go']['main']['App']['ApplyPatch'](arg1, arg2);
}

export function DetectAsar() {
  return window['go']['main']['App']['DetectAsar']();
}

export function GetPatches() {
  return window['go']['main']['App']['GetPatches']();
}

export function SelectAsar(arg1) {
  return window['go']['main']['App']['SelectAsar'](arg1);
}
